import Head from "next/head";
import Image from "next/image";
import AstroLogo from "../public/astrologo.png";

export default function Home() {
  return (
    <div className="bg-gradient-to-tr from-blue-500 to-red-500 min-h-screen">
      <Head>
        <title>Astro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-full md:h-screen w-full container mx-auto px-5 flex flex-wrap content-center justify-center">
        <div className="flex md:flex-row flex-col content-center items-center justify-around">
          <div>
            <Image src={AstroLogo} alt="astrologo" />
          </div>

          <div className="py-12 p-10 flex flex-col justify-around bg-white rounded-2xl shadow-xl z-20">
            <div>
              <h1 className="text-xl md:text-3xl font-regular text-center mb-4 cursor-pointer">
                Form VVIP
              </h1>
            </div>
            <div className="space-y-4">
              <input
                className="w-full py-3 border-b px-2 focus:outline-none"
                type="text"
                placeholder="FullName"
                required
              />
              <input
                className="w-full py-3 border-b px-2 focus:outline-none"
                type="email"
                placeholder="johndoe@gmail.com"
                required
              />
              <input
                className="w-full py-3 border-b px-2 focus:outline-none"
                type="text"
                placeholder="PhoneNumber"
                required
              />
            </div>
            <div className="text-center mt-6">
              <button className="py-3 w-full text-lg md:text-xl text-white bg-red-500 rounded-2xl">
                SUBMIT
              </button>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
