import Head from "next/head";
import Image from "next/image";
import AstroLogo from "../public/astrologosmall.png";
import Wallpaper from "../public/wallpaper.png";

export default function Home() {
  return (
    <div className="bg-gradient-to-tr from-blue-500 to-red-500 min-h-screen min-w-screen flex items-center justify-center">
      <Head>
        <title>Astro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="rounded-3xl shadow-xl ">
        <div className="flex flex-col md:flex-row w-screen md:w-full justify-center bg-white ">
          <div className="flex flex-col w-full md:w-3/4 justify-between bg-white ">
            <div className="bg-red-500 text-center">
              <Image
                src={AstroLogo}
                width="150"
                height="150"
                alt="astro logo sm"
              />
              <h1 className="text-xl md:text-3xl font-bold text-center mb-4 cursor-pointer text-white">
                VVIP Form
              </h1>
            </div>
            <div className="p-10 py-12">
              <div className="flex flex-col space-y-4">
                <input
                  className="w-full py-3 border-b px-2 focus:outline-none"
                  type="text"
                  placeholder="FullName"
                  required
                />
                <input
                  className="w-full py-3 border-b px-2 focus:outline-none"
                  type="email"
                  placeholder="johndoe@gmail.com"
                  required
                />
                <input
                  className="w-full py-3 border-b px-2 focus:outline-none"
                  type="text"
                  placeholder="PhoneNumber"
                  required
                />
                <select className="border border-gray-200 rounded-full text-gray-600 h-10 pl-5 pr-10 bg-white hover:border-gray-400 focus:outline-none appearance-none">
                  <option>Location</option>
                  <option>Red</option>
                  <option>Blue</option>
                  <option>Yellow</option>
                  <option>Black</option>
                  <option>Orange</option>
                  <option>Purple</option>
                  <option>Gray</option>
                  <option>White</option>
                </select>
              </div>
              <div className="text-center mt-6">
                <button className="py-3 w-full text-lg md:text-xl text-white bg-red-500 rounded-2xl">
                  SUBMIT
                </button>
              </div>
            </div>
          </div>
          <div className="h-full w-full hidden md:block">
            <Image
              height="800px"
              width="800px"
              src={Wallpaper}
              alt="astrologo"
            />
          </div>
        </div>
      </main>
    </div>
  );
}
